"""empty message

Revision ID: b0d3ea4be8f4
Revises: 676630c4b1a9
Create Date: 2023-02-02 10:56:35.204894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d3ea4be8f4'
down_revision = '676630c4b1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stocks', ['symbol'])
    op.alter_column('transactions', 'order_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'is_open',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'account_value',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('users', 'buying_power',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'buying_power',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('users', 'account_value',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('transactions', 'is_open',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('transactions', 'order_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'stocks', type_='unique')
    # ### end Alembic commands ###